name: Daily Full Test Suite

on:
  schedule:
    - cron: '0 8 * * *'
  # Allow manual trigger from the Actions tab for debugging
  workflow_dispatch:

jobs:
  tests-full:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: dolphindes
          environment-file: dolphindes.yml
          python-version: "3.10"
          auto-activate-base: false
          use-mamba: true 
          cache-environment: true

      - name: Install Dev Dependencies
        shell: bash -l {0}
        run: |
          pip install .[dev]

      - name: Run Full Test Suite
        shell: bash -l {0}
        run: pytest --cov=dolphindes --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: physical-design-bounds/dolphindes
          files: ./coverage.xml
          fail_ci_if_error: true
