name: "CI: Tests"

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  tests-fast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: dolphindes
          environment-file: dolphindes.yml
          python-version: "3.10"
          auto-activate-base: false
          use-mamba: true
          cache-environment: true

      - name: Install Dev Dependencies
        shell: bash -l {0}
        run: pip install .[dev]

      - name: Run Pytest (Fast only)
        shell: bash -l {0}
        run: pytest -m "not slow" --cov=dolphindes --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: physical-design-bounds/dolphindes
          files: ./coverage.xml
          fail_ci_if_error: false
